export const HATCH_ERRORS = {
  ERROR_HATCH_NOT_OPENED: "HATCH_NOT_OPENED",
  ERROR_HATCH_GOAL_NOT_REACHED: "HATCH_GOAL_NOT_REACHED",
  ERROR_HATCH_NOT_CLOSED: "HATCH_NOT_CLOSED",
  ERROR_CONTRIBUTION_NOT_MADE: "CONTRIBUTION_NOT_MADE",
};

export const TOKEN_ERRORS = {
  ERROR_APPROVAL_MISMATCH: "APPROVAL_MISMATCH",
};

export const IMPACT_HOURS_ERRORS = {
  ERROR_ALL_TOKENS_NOT_DESTROYED: "ALL_TOKENS_NOT_DESTROYED",
  ERROR_CLAIMED_REWARDS_MISMATCH: "CLAIMED_REWARDS_MISMATCH",
};
